#= require ./tevye/store
#= require_tree ./tevye/models
#= require_tree ./tevye/controllers
#= require_tree ./tevye/views
#= require_tree ./tevye/helpers
#= require_tree ./tevye/templates
#= require_tree ./tevye/routes
#= require ./tevye/router
#= require_self
